# Site Settings
lang: en
title: Online Tools for astronomical unit conversions
tagline: 
email: "alexis.yslau@gmail.com"
description: >
Online calculator for unit conversions
author: Alexis Lau
#baseurl: "/"
url: "https://alexisyslau.github.io/astrotool.github.io/"
permalink: pretty
favicon: /img/nemo-favicon.png
paginate: 9
paginate_path: "/news/page:num"
livereload: true
markdown: kramdown
highlighter: rouge
footer_menu: footer_menu
hide_share_buttons: true
# theme_color: '#008cba'
# fixed_navbar: top

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - kramdown
  - kramdown-parser-gfm
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

theme: jekyll-theme-hacker